# map metagenomic reads to reference algae genome

# HTCondor Universe
universe = vanilla
log = logs/algae_mapping_$(Cluster).log
error = errs/algae_mapping_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX") && (Target.HasGluster == true) && (OpSysMajorVer =?= 7)

# Exectuables
executable = executables/map-metas-to-algae.sh
arguments = $(ref) $(meta) $(outname)
output = outs/algae_mapping_$(Cluster).out

# Transferring Files
# should_transfer_files = YES
# when_to_transfer_output = ON_EXIT
transfer_input_files = /home/emcdaniel/software/BBMap_38.07.tar.gz,/home/emcdaniel/software/samtools.tar.gz,/home/emcdaniel/software/python.tar.gz,scripts/calc-mapping-stats.py,scripts/countBases.py

# Compute resources
request_cpus = 4
request_memory = 10GB
request_disk = 50GB


queue ref,meta,outname from metadata/queues/algae-mapping-combos.txt
